VERSION: 20160904
CIPHER:
  WEBSITE_URL: https://biotcm.github.io/CIPHER/
HGNC:
  DOWNLOAD_URL: https://www.genenames.org/cgi-bin/download/custom?col=gd_hgnc_id&col=gd_app_sym&col=gd_app_name&col=gd_prev_sym&col=gd_aliases&col=gd_pub_refseq_ids&col=md_eg_id&col=md_refseq_id&col=md_prot_id&col=md_ensembl_id&status=Approved&status_opt=2&where=&order_by=gd_hgnc_id&format=text&limit=&hgnc_dbtag=on&submit=submit
OMIM:
  API_KEY: 30ErS0YOSF-6OA381_qVMQ
